# Generated by Django 3.1.5 on 2021-01-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='total_shares',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total Shares'),
        ),
    ]
